### ISSUE TITLE
✨ [Feature] 빌드파일  추가

### ISSUE THREAD

**Issue by suugit** [Parrotalk/Parrotalk_BE#3]
### Description

서버 배포에 필요한 빌드 및 모니터링 파일 추가

### Todo

- [ ] 도커기반 빌드파일 작성
- [ ] 모니터링 패키지 추가
- [ ] 수동 빌드위한 스크립트 작성
